import type { Initiative, Owner, Theme } from "./types";

export const OWNERS: Owner[] = [
  { id: "u-magali", name: "Magali Roux", role: "Head of Product" },
  { id: "u-helene", name: "Hélène Dupont", role: "Senior PM" },
  { id: "u-seimour", name: "Seimour Karim", role: "Product Manager" },
  { id: "u-nadia", name: "Nadia Belhaj", role: "PM, Platform" },
  { id: "u-tom", name: "Tom Verhoeven", role: "Engineering Manager" },
];

export const THEMES: Theme[] = [
  {
    id: "t-ai",
    name: "AI-led Experimentation",
    description: "Make testing and personalization smarter with predictive models.",
    color: "lime",
  },
  {
    id: "t-fm",
    name: "Feature Management",
    description: "Ship and control features safely with flags and rollouts.",
    color: "blue",
  },
  {
    id: "t-web",
    name: "Web Experimentation",
    description: "Faster, flicker-free client-side and server-side testing.",
    color: "green",
  },
  {
    id: "t-trust",
    name: "Data & Trust",
    description: "Statistical rigor, privacy, and results people can rely on.",
    color: "pink",
  },
  {
    id: "t-platform",
    name: "Platform & Scale",
    description: "Performance, reliability, and enterprise readiness.",
    color: "orange",
  },
];

export const INITIATIVES: Initiative[] = [
  {
    id: "i-pbx",
    title: "PBX predictive targeting v2",
    summary: "Second-generation predictive segments powering audience targeting across web and feature flags.",
    problem: "Manual segment building is slow and misses high-intent users; teams want targeting that adapts automatically.",
    expectedOutcome: "Adopting accounts see a measurable lift in conversion on personalized experiences within one quarter.",
    status: "in_development",
    ownerId: "u-magali",
    team: "Tech & Perso Builders",
    themeId: "t-ai",
    strategicGoal: "Lead the market on AI-driven experimentation",
    scores: { reach: 10, impact: 3, confidence: 0.8, effort: 8 },
    health: "on_track",
    targetStart: "2026-04-01",
    targetEnd: "2026-09-30",
    deliveryLinks: [
      { id: "d1", label: "PBX-1420", url: "https://kameleoon.atlassian.net/browse/PBX-1420", type: "redmine" },
      { id: "d2", label: "Model spec", url: "https://www.notion.so/kameleoon/pbx-v2", type: "spec" },
    ],
    dependsOn: ["i-stats"],
    visibility: "external",
    notes: "Legal reviewing model card language before we can name accuracy figures externally.",
    updatedAt: "2026-07-02T09:20:00Z",
    archived: false,
  },
  {
    id: "i-flicker",
    title: "Zero-flicker rendering engine",
    summary: "Rewrite the client-side apply path to eliminate flicker on slow connections.",
    problem: "Flicker on first paint undermines trust in client-side tests, especially on media sites.",
    expectedOutcome: "Sub-50ms apply time on P75 pages; flicker complaints drop to near zero.",
    status: "in_development",
    ownerId: "u-helene",
    team: "Visual Builders",
    themeId: "t-web",
    strategicGoal: "Best-in-class web testing experience",
    scores: { reach: 10, impact: 3, confidence: 1, effort: 5 },
    health: "on_track",
    targetStart: "2026-05-01",
    targetEnd: "2026-08-15",
    deliveryLinks: [
      { id: "d3", label: "WEB-980", url: "https://kameleoon.atlassian.net/browse/WEB-980", type: "redmine" },
    ],
    dependsOn: [],
    visibility: "external",
    notes: "Perf budget agreed with SDK team. Watch bundle size regression.",
    updatedAt: "2026-07-06T14:05:00Z",
    archived: false,
  },
  {
    id: "i-stats",
    title: "Bayesian stats engine GA",
    summary: "Graduate the Bayesian results engine from beta to general availability.",
    problem: "Customers want faster, more interpretable results than frequentist-only reporting allows.",
    expectedOutcome: "Bayesian reporting available to all plans with clear decision guidance.",
    status: "solution_framing",
    ownerId: "u-nadia",
    team: "Tech & Perso Builders",
    themeId: "t-trust",
    strategicGoal: "Results people can trust",
    scores: { reach: 10, impact: 2, confidence: 0.5, effort: 8 },
    health: "at_risk",
    targetStart: "2026-03-01",
    targetEnd: "2026-07-31",
    deliveryLinks: [
      { id: "d4", label: "Stats validation", url: "https://www.notion.so/kameleoon/stats-ga", type: "other" },
    ],
    dependsOn: [],
    visibility: "internal",
    notes: "Validation dataset behind schedule; risk to July GA. Considering a two-week slip.",
    updatedAt: "2026-07-07T08:40:00Z",
    archived: false,
  },
  {
    id: "i-flags-approvals",
    title: "Feature flag change approvals",
    summary: "Add approval workflows and audit trails to flag changes in production.",
    problem: "Enterprise accounts need governance before flags touch production traffic.",
    expectedOutcome: "Approvals, roles, and full audit history available for flag changes.",
    status: "planned",
    ownerId: "u-seimour",
    team: "App System",
    themeId: "t-fm",
    strategicGoal: "Enterprise-grade feature control",
    scores: { reach: 8, impact: 2, confidence: 0.8, effort: 5 },
    health: "on_track",
    targetStart: "2026-08-01",
    targetEnd: "2026-11-30",
    deliveryLinks: [
      { id: "d5", label: "FM-233", url: "https://kameleoon.atlassian.net/browse/FM-233", type: "redmine" },
    ],
    dependsOn: [],
    visibility: "external",
    notes: "",
    updatedAt: "2026-06-28T11:15:00Z",
    archived: false,
  },
  {
    id: "i-sdk-edge",
    title: "Edge SDK for server-side testing",
    summary: "Ship an edge-optimized SDK for Cloudflare Workers and Vercel Edge.",
    problem: "Teams on edge runtimes lack a low-latency way to run server-side experiments.",
    expectedOutcome: "Officially supported edge SDK with <5ms decision latency.",
    status: "opportunity_framing",
    ownerId: "u-tom",
    team: "App System",
    themeId: "t-platform",
    strategicGoal: "Meet developers where they build",
    scores: { reach: 8, impact: 2, confidence: 0.8, effort: 6 },
    health: "on_track",
    targetStart: "2026-09-01",
    targetEnd: "2026-12-31",
    deliveryLinks: [],
    dependsOn: ["i-flicker"],
    visibility: "internal",
    notes: "Sequenced after rendering engine work frees up SDK capacity.",
    updatedAt: "2026-06-20T16:00:00Z",
    archived: false,
  },
  {
    id: "i-personalization",
    title: "AI content personalization",
    summary: "Generate and test personalized copy variants with an AI assist.",
    problem: "Building many variants by hand is expensive; teams under-test personalization.",
    expectedOutcome: "Users create tested personalization campaigns in minutes, not days.",
    status: "opportunity_framing",
    ownerId: "u-magali",
    team: "Tech & Perso Builders",
    themeId: "t-ai",
    strategicGoal: "Lead the market on AI-driven experimentation",
    scores: { reach: 10, impact: 3, confidence: 0.5, effort: 10 },
    health: "at_risk",
    targetStart: "2026-10-01",
    targetEnd: "2027-02-28",
    deliveryLinks: [
      { id: "d6", label: "Discovery doc", url: "https://www.notion.so/kameleoon/ai-personalization", type: "notion" },
    ],
    dependsOn: ["i-pbx"],
    visibility: "internal",
    notes: "Still in discovery. Depends on PBX v2 shipping the segment API.",
    updatedAt: "2026-07-01T10:30:00Z",
    archived: false,
  },
  {
    id: "i-consent",
    title: "Consent-mode analytics bridge",
    summary: "Respect consent signals end-to-end and reconcile with analytics partners.",
    problem: "Privacy regulations require consent-aware measurement without breaking reporting.",
    expectedOutcome: "Consent-aware data collection with no gaps in trusted reporting.",
    status: "in_development",
    ownerId: "u-nadia",
    team: "Tech & Perso Builders",
    themeId: "t-trust",
    strategicGoal: "Privacy-first by design",
    scores: { reach: 10, impact: 1, confidence: 1, effort: 4 },
    health: "on_track",
    targetStart: "2026-06-01",
    targetEnd: "2026-09-15",
    deliveryLinks: [
      { id: "d7", label: "DATA-77", url: "https://kameleoon.atlassian.net/browse/DATA-77", type: "redmine" },
    ],
    dependsOn: [],
    visibility: "internal",
    notes: "Coordinating with the Google consent-mode v2 timeline.",
    updatedAt: "2026-07-05T13:10:00Z",
    archived: false,
  },
  {
    id: "i-mobile",
    title: "Mobile app experimentation",
    summary: "Native iOS/Android experimentation with a unified results model.",
    problem: "Mobile teams run tests in a separate tool with inconsistent metrics.",
    expectedOutcome: "One experimentation model spanning web and mobile.",
    status: "planned",
    ownerId: "u-seimour",
    team: "App System",
    themeId: "t-fm",
    strategicGoal: "One platform across surfaces",
    scores: { reach: 10, impact: 2, confidence: 0.5, effort: 12 },
    health: "blocked",
    targetStart: "2026-11-01",
    targetEnd: "2027-03-31",
    deliveryLinks: [],
    dependsOn: [],
    visibility: "internal",
    notes: "Needs staffing decision in Q4 planning.",
    updatedAt: "2026-06-15T09:00:00Z",
    archived: false,
  },
  {
    id: "i-onboarding",
    title: "Guided onboarding revamp",
    summary: "Rebuild first-run onboarding so new accounts launch a test in day one.",
    problem: "Time-to-first-test is too long; new accounts stall during setup.",
    expectedOutcome: "Median time-to-first-test cut in half.",
    status: "released",
    ownerId: "u-helene",
    team: "Visual Builders",
    themeId: "t-web",
    strategicGoal: "Best-in-class web testing experience",
    scores: { reach: 10, impact: 1, confidence: 1, effort: 3 },
    health: "on_track",
    targetStart: "2026-02-01",
    targetEnd: "2026-05-15",
    deliveryLinks: [
      { id: "d8", label: "Launch notes", url: "https://www.notion.so/kameleoon/onboarding-launch", type: "other" },
    ],
    dependsOn: [],
    visibility: "external",
    notes: "Shipped. Monitoring activation funnel for the next month.",
    updatedAt: "2026-05-16T17:45:00Z",
    archived: false,
  },
  {
    id: "i-warehouse",
    title: "Warehouse-native export",
    summary: "Stream raw experiment data to Snowflake and BigQuery.",
    problem: "Data teams want experiment data in their warehouse for custom analysis.",
    expectedOutcome: "Reliable, documented exports to major warehouses.",
    status: "solution_framing",
    ownerId: "u-tom",
    team: "App System",
    themeId: "t-platform",
    strategicGoal: "Open, composable data",
    scores: { reach: 8, impact: 1, confidence: 0.8, effort: 4 },
    health: "on_track",
    targetStart: "2026-09-15",
    targetEnd: "2026-12-15",
    deliveryLinks: [],
    dependsOn: ["i-consent"],
    visibility: "internal",
    notes: "",
    updatedAt: "2026-06-18T12:00:00Z",
    archived: false,
  },
  {
    id: "i-cro-assist",
    title: "CRO assistant (beta)",
    summary: "An assistant that suggests test ideas from site behavior and past results.",
    problem: "Teams run out of test ideas and repeat low-impact experiments.",
    expectedOutcome: "A steady stream of ranked, evidence-backed test ideas.",
    status: "in_development",
    ownerId: "u-magali",
    team: "Tech & Perso Builders",
    themeId: "t-ai",
    strategicGoal: "Lead the market on AI-driven experimentation",
    scores: { reach: 10, impact: 2, confidence: 0.5, effort: 6 },
    health: "at_risk",
    targetStart: "2026-05-15",
    targetEnd: "2026-08-31",
    deliveryLinks: [
      { id: "d9", label: "AI-51", url: "https://kameleoon.atlassian.net/browse/AI-51", type: "redmine" },
    ],
    dependsOn: ["i-stats"],
    visibility: "internal",
    notes: "Quality of suggestions inconsistent; may narrow beta scope.",
    updatedAt: "2026-07-04T15:30:00Z",
    archived: false,
  },
  {
    id: "i-rollback",
    title: "One-click experiment rollback",
    summary: "Instantly revert a running experiment or flag from any results view.",
    problem: "Reverting a bad variant takes too many steps during incidents.",
    expectedOutcome: "Single action to safely roll back, with confirmation and audit.",
    status: "released",
    ownerId: "u-seimour",
    team: "App System",
    themeId: "t-fm",
    strategicGoal: "Enterprise-grade feature control",
    scores: { reach: 8, impact: 1, confidence: 1, effort: 2 },
    health: "on_track",
    targetStart: "2026-03-15",
    targetEnd: "2026-05-01",
    deliveryLinks: [
      { id: "d10", label: "FM-198", url: "https://kameleoon.atlassian.net/browse/FM-198", type: "redmine" },
    ],
    dependsOn: [],
    visibility: "external",
    notes: "Shipped and well received in support tickets.",
    updatedAt: "2026-05-02T10:00:00Z",
    archived: false,
  },
  {
    id: "i-sso",
    title: "SCIM provisioning & SSO groups",
    summary: "Automated user provisioning and group-to-role mapping via SCIM.",
    problem: "Large accounts manage users by hand; access drifts out of sync.",
    expectedOutcome: "Users and roles stay in sync with the customer's IdP automatically.",
    status: "planned",
    ownerId: "u-nadia",
    team: "App System",
    themeId: "t-platform",
    strategicGoal: "Enterprise readiness",
    scores: { reach: 8, impact: 1, confidence: 1, effort: 3 },
    health: "on_track",
    targetStart: "2026-08-15",
    targetEnd: "2026-10-31",
    deliveryLinks: [],
    dependsOn: [],
    visibility: "internal",
    notes: "Requested by two enterprise renewals this year.",
    updatedAt: "2026-06-25T14:20:00Z",
    archived: false,
  },
];
