import type { Initiative, Owner, Theme } from "./types";

export const OWNERS: Owner[] = [
  { id: "u-magali", name: "Magali", surname: "Roux", role: "Head of Product", email: "mroux@example.com", team: "App System" },
  { id: "u-helene", name: "Hélène", surname: "Dupont", role: "Senior PM", email: "hdupont@example.com", team: "Tech & Perso Builders" },
  { id: "u-seimour", name: "Seimour", surname: "Karim", role: "Product Manager", email: "skarim@example.com", team: "Visual Builders" },
  { id: "u-nadia", name: "Nadia", surname: "Belhaj", role: "PM, Platform", email: "nbelhaj@example.com", team: "App System" },
  { id: "u-tom", name: "Tom", surname: "Verhoeven", role: "Engineering Manager", email: "tverhoeven@example.com", team: "Tech & Perso Builders" },
  { id: "u-lea", name: "Léa", surname: "Fontaine", role: "Senior PM", email: "lfontaine@example.com", team: "Tech & Perso Builders" },
  { id: "u-marc", name: "Marc", surname: "Dubois", role: "Staff Engineer", email: "mdubois@example.com", team: "App System" },
  { id: "u-sofia", name: "Sofia", surname: "Almeida", role: "Design Lead", email: "salmeida@example.com", team: "Visual Builders" },
];

export const THEMES: Theme[] = [
  {
    id: "t-ai",
    name: "AI-led Experimentation",
    description: "Make testing and personalization smarter with predictive models.",
    color: "lime",
  },
  {
    id: "t-fm",
    name: "Feature Management",
    description: "Ship and control features safely with flags and rollouts.",
    color: "blue",
  },
  {
    id: "t-web",
    name: "Web Experimentation",
    description: "Faster, flicker-free client-side and server-side testing.",
    color: "green",
  },
  {
    id: "t-trust",
    name: "Data & Trust",
    description: "Statistical rigor, privacy, and results people can rely on.",
    color: "pink",
  },
  {
    id: "t-platform",
    name: "Platform & Scale",
    description: "Performance, reliability, and enterprise readiness.",
    color: "orange",
  },
  {
    id: "t-dx",
    name: "Developer Experience",
    description: "SDKs, docs, and APIs that make integration effortless.",
    color: "beige",
  },
];

export const INITIATIVES: Initiative[] = [
  {
    id: "i-pbx",
    title: "PBX predictive targeting v2",
    summary: "Second-generation predictive segments powering audience targeting across web and feature flags.",
    problem: "Manual segment building is slow and misses high-intent users; teams want targeting that adapts automatically.",
    expectedOutcome: "Adopting accounts see a measurable lift in conversion on personalized experiences within one quarter.",
    status: "in_development",
    ownerId: "u-magali",
    team: "Tech & Perso Builders",
    themeId: "t-ai",
    strategicGoal: "Lead the market on AI-driven experimentation",
    scores: { demand: 1000, impact: 10, viability: 0.8, effort: 8 },
    health: "on_track",
    targetStart: "2026-04-01",
    targetEnd: "2026-09-30",
    deliveryLinks: [
      { id: "d1", label: "PBX-1420", url: "https://example.atlassian.net/browse/PBX-1420", type: "redmine" },
      { id: "d2", label: "Model spec", url: "https://www.notion.so/example/pbx-v2", type: "spec" },
    ],
    dependsOn: ["i-stats"],
    visibility: "external",
    notes: "Legal reviewing model card language before we can name accuracy figures externally.",
    updatedAt: "2026-07-02T09:20:00Z",
    archived: false,
  },
  {
    id: "i-flicker",
    title: "Zero-flicker rendering engine",
    summary: "Rewrite the client-side apply path to eliminate flicker on slow connections.",
    problem: "Flicker on first paint undermines trust in client-side tests, especially on media sites.",
    expectedOutcome: "Sub-50ms apply time on P75 pages; flicker complaints drop to near zero.",
    status: "in_development",
    ownerId: "u-helene",
    team: "Visual Builders",
    themeId: "t-web",
    strategicGoal: "Best-in-class web testing experience",
    scores: { demand: 1000, impact: 10, viability: 1, effort: 5 },
    health: "on_track",
    targetStart: "2026-05-01",
    targetEnd: "2026-08-15",
    deliveryLinks: [
      { id: "d3", label: "WEB-980", url: "https://example.atlassian.net/browse/WEB-980", type: "redmine" },
    ],
    dependsOn: [],
    visibility: "external",
    notes: "Perf budget agreed with SDK team. Watch bundle size regression.",
    updatedAt: "2026-07-06T14:05:00Z",
    archived: false,
  },
  {
    id: "i-stats",
    title: "Bayesian stats engine GA",
    summary: "Graduate the Bayesian results engine from beta to general availability.",
    problem: "Customers want faster, more interpretable results than frequentist-only reporting allows.",
    expectedOutcome: "Bayesian reporting available to all plans with clear decision guidance.",
    status: "solution_framing",
    ownerId: "u-nadia",
    team: "Tech & Perso Builders",
    themeId: "t-trust",
    strategicGoal: "Results people can trust",
    scores: { demand: 1000, impact: 3, viability: 0.5, effort: 8 },
    health: "at_risk",
    targetStart: "2026-03-01",
    targetEnd: "2026-07-31",
    deliveryLinks: [
      { id: "d4", label: "Stats validation", url: "https://www.notion.so/example/stats-ga", type: "other" },
    ],
    dependsOn: [],
    visibility: "internal",
    notes: "Validation dataset behind schedule; risk to July GA. Considering a two-week slip.",
    updatedAt: "2026-07-07T08:40:00Z",
    archived: false,
  },
  {
    id: "i-flags-approvals",
    title: "Feature flag change approvals",
    summary: "Add approval workflows and audit trails to flag changes in production.",
    problem: "Enterprise accounts need governance before flags touch production traffic.",
    expectedOutcome: "Approvals, roles, and full audit history available for flag changes.",
    status: "planned",
    ownerId: "u-seimour",
    team: "App System",
    themeId: "t-fm",
    strategicGoal: "Enterprise-grade feature control",
    scores: { demand: 250, impact: 3, viability: 0.8, effort: 5 },
    health: "on_track",
    targetStart: "2026-08-01",
    targetEnd: "2026-11-30",
    deliveryLinks: [
      { id: "d5", label: "FM-233", url: "https://example.atlassian.net/browse/FM-233", type: "redmine" },
    ],
    dependsOn: [],
    visibility: "external",
    notes: "",
    updatedAt: "2026-06-28T11:15:00Z",
    archived: false,
  },
  {
    id: "i-sdk-edge",
    title: "Edge SDK for server-side testing",
    summary: "Ship an edge-optimized SDK for Cloudflare Workers and Vercel Edge.",
    problem: "Teams on edge runtimes lack a low-latency way to run server-side experiments.",
    expectedOutcome: "Officially supported edge SDK with <5ms decision latency.",
    status: "opportunity_framing",
    ownerId: "u-tom",
    team: "App System",
    themeId: "t-platform",
    strategicGoal: "Meet developers where they build",
    scores: { demand: 250, impact: 3, viability: 0.8, effort: 6 },
    health: "on_track",
    targetStart: "2026-09-01",
    targetEnd: "2026-12-31",
    deliveryLinks: [],
    dependsOn: ["i-flicker"],
    visibility: "internal",
    notes: "Sequenced after rendering engine work frees up SDK capacity.",
    updatedAt: "2026-06-20T16:00:00Z",
    archived: false,
  },
  {
    id: "i-personalization",
    title: "AI content personalization",
    summary: "Generate and test personalized copy variants with an AI assist.",
    problem: "Building many variants by hand is expensive; teams under-test personalization.",
    expectedOutcome: "Users create tested personalization campaigns in minutes, not days.",
    status: "opportunity_framing",
    ownerId: "u-magali",
    team: "Tech & Perso Builders",
    themeId: "t-ai",
    strategicGoal: "Lead the market on AI-driven experimentation",
    scores: { demand: 1000, impact: 10, viability: 0.5, effort: 10 },
    health: "at_risk",
    targetStart: "2026-10-01",
    targetEnd: "2027-02-28",
    deliveryLinks: [
      { id: "d6", label: "Discovery doc", url: "https://www.notion.so/example/ai-personalization", type: "notion" },
    ],
    dependsOn: ["i-pbx"],
    visibility: "internal",
    notes: "Still in discovery. Depends on PBX v2 shipping the segment API.",
    updatedAt: "2026-07-01T10:30:00Z",
    archived: false,
  },
  {
    id: "i-consent",
    title: "Consent-mode analytics bridge",
    summary: "Respect consent signals end-to-end and reconcile with analytics partners.",
    problem: "Privacy regulations require consent-aware measurement without breaking reporting.",
    expectedOutcome: "Consent-aware data collection with no gaps in trusted reporting.",
    status: "in_development",
    ownerId: "u-nadia",
    team: "Tech & Perso Builders",
    themeId: "t-trust",
    strategicGoal: "Privacy-first by design",
    scores: { demand: 1000, impact: 1, viability: 1, effort: 4 },
    health: "on_track",
    targetStart: "2026-06-01",
    targetEnd: "2026-09-15",
    deliveryLinks: [
      { id: "d7", label: "DATA-77", url: "https://example.atlassian.net/browse/DATA-77", type: "redmine" },
    ],
    dependsOn: [],
    visibility: "internal",
    notes: "Coordinating with the Google consent-mode v2 timeline.",
    updatedAt: "2026-07-05T13:10:00Z",
    archived: false,
  },
  {
    id: "i-mobile",
    title: "Mobile app experimentation",
    summary: "Native iOS/Android experimentation with a unified results model.",
    problem: "Mobile teams run tests in a separate tool with inconsistent metrics.",
    expectedOutcome: "One experimentation model spanning web and mobile.",
    status: "planned",
    ownerId: "u-seimour",
    team: "App System",
    themeId: "t-fm",
    strategicGoal: "One platform across surfaces",
    scores: { demand: 1000, impact: 3, viability: 0.5, effort: 12 },
    health: "blocked",
    targetStart: "2026-11-01",
    targetEnd: "2027-03-31",
    deliveryLinks: [],
    dependsOn: [],
    visibility: "internal",
    notes: "Needs staffing decision in Q4 planning.",
    updatedAt: "2026-06-15T09:00:00Z",
    archived: false,
  },
  {
    id: "i-onboarding",
    title: "Guided onboarding revamp",
    summary: "Rebuild first-run onboarding so new accounts launch a test in day one.",
    problem: "Time-to-first-test is too long; new accounts stall during setup.",
    expectedOutcome: "Median time-to-first-test cut in half.",
    status: "released",
    ownerId: "u-helene",
    team: "Visual Builders",
    themeId: "t-web",
    strategicGoal: "Best-in-class web testing experience",
    scores: { demand: 1000, impact: 1, viability: 1, effort: 3 },
    health: "on_track",
    targetStart: "2026-02-01",
    targetEnd: "2026-05-15",
    deliveryLinks: [
      { id: "d8", label: "Launch notes", url: "https://www.notion.so/example/onboarding-launch", type: "other" },
    ],
    dependsOn: [],
    visibility: "external",
    notes: "Shipped. Monitoring activation funnel for the next month.",
    updatedAt: "2026-05-16T17:45:00Z",
    archived: false,
  },
  {
    id: "i-warehouse",
    title: "Warehouse-native export",
    summary: "Stream raw experiment data to Snowflake and BigQuery.",
    problem: "Data teams want experiment data in their warehouse for custom analysis.",
    expectedOutcome: "Reliable, documented exports to major warehouses.",
    status: "solution_framing",
    ownerId: "u-tom",
    team: "App System",
    themeId: "t-platform",
    strategicGoal: "Open, composable data",
    scores: { demand: 250, impact: 1, viability: 0.8, effort: 4 },
    health: "on_track",
    targetStart: "2026-09-15",
    targetEnd: "2026-12-15",
    deliveryLinks: [],
    dependsOn: ["i-consent"],
    visibility: "internal",
    notes: "",
    updatedAt: "2026-06-18T12:00:00Z",
    archived: false,
  },
  {
    id: "i-cro-assist",
    title: "CRO assistant (beta)",
    summary: "An assistant that suggests test ideas from site behavior and past results.",
    problem: "Teams run out of test ideas and repeat low-impact experiments.",
    expectedOutcome: "A steady stream of ranked, evidence-backed test ideas.",
    status: "in_development",
    ownerId: "u-magali",
    team: "Tech & Perso Builders",
    themeId: "t-ai",
    strategicGoal: "Lead the market on AI-driven experimentation",
    scores: { demand: 1000, impact: 3, viability: 0.5, effort: 6 },
    health: "at_risk",
    targetStart: "2026-05-15",
    targetEnd: "2026-08-31",
    deliveryLinks: [
      { id: "d9", label: "AI-51", url: "https://example.atlassian.net/browse/AI-51", type: "redmine" },
    ],
    dependsOn: ["i-stats"],
    visibility: "internal",
    notes: "Quality of suggestions inconsistent; may narrow beta scope.",
    updatedAt: "2026-07-04T15:30:00Z",
    archived: false,
  },
  {
    id: "i-rollback",
    title: "One-click experiment rollback",
    summary: "Instantly revert a running experiment or flag from any results view.",
    problem: "Reverting a bad variant takes too many steps during incidents.",
    expectedOutcome: "Single action to safely roll back, with confirmation and audit.",
    status: "released",
    ownerId: "u-seimour",
    team: "App System",
    themeId: "t-fm",
    strategicGoal: "Enterprise-grade feature control",
    scores: { demand: 250, impact: 1, viability: 1, effort: 2 },
    health: "on_track",
    targetStart: "2026-03-15",
    targetEnd: "2026-05-01",
    deliveryLinks: [
      { id: "d10", label: "FM-198", url: "https://example.atlassian.net/browse/FM-198", type: "redmine" },
    ],
    dependsOn: [],
    visibility: "external",
    notes: "Shipped and well received in support tickets.",
    updatedAt: "2026-05-02T10:00:00Z",
    archived: false,
  },
  {
    id: "i-sso",
    title: "SCIM provisioning & SSO groups",
    summary: "Automated user provisioning and group-to-role mapping via SCIM.",
    problem: "Large accounts manage users by hand; access drifts out of sync.",
    expectedOutcome: "Users and roles stay in sync with the customer's IdP automatically.",
    status: "planned",
    ownerId: "u-nadia",
    team: "App System",
    themeId: "t-platform",
    strategicGoal: "Enterprise readiness",
    scores: { demand: 250, impact: 1, viability: 1, effort: 3 },
    health: "on_track",
    targetStart: "2026-08-15",
    targetEnd: "2026-10-31",
    deliveryLinks: [],
    dependsOn: [],
    visibility: "internal",
    notes: "Requested by two enterprise renewals this year.",
    updatedAt: "2026-06-25T14:20:00Z",
    archived: false,
  },
  {
    id: "i-visual-editor",
    title: "Visual editor 3.0",
    summary: "A faster, block-based visual editor for building experiments without code.",
    problem: "The current editor struggles on complex pages and slows non-technical users down.",
    expectedOutcome: "Non-technical users build and launch a variant in under ten minutes.",
    status: "opportunity_framing",
    ownerId: "u-sofia",
    team: "Visual Builders",
    themeId: "t-web",
    strategicGoal: "Best-in-class web testing experience",
    scores: { demand: 250, impact: 3, viability: 0.8, effort: 7 },
    health: "on_track",
    targetStart: "2026-09-01",
    targetEnd: "2027-01-15",
    deliveryLinks: [
      { id: "d11", label: "VIS-120", url: "https://example.atlassian.net/browse/VIS-120", type: "redmine" },
      { id: "d12", label: "Editor redesign", url: "https://www.figma.com/file/example/editor-3", type: "figma" },
    ],
    dependsOn: [],
    visibility: "external",
    notes: "Design system alignment needed before build.",
    updatedAt: "2026-06-30T10:00:00Z",
    archived: false,
  },
  {
    id: "i-holdout",
    title: "Global holdout groups",
    summary: "Reserve a global holdout audience to measure the true incremental impact of all experiments.",
    problem: "Teams can't quantify the aggregate lift of their experimentation program.",
    expectedOutcome: "A trustworthy program-level incrementality number per account.",
    status: "planned",
    ownerId: "u-nadia",
    team: "Tech & Perso Builders",
    themeId: "t-trust",
    strategicGoal: "Results people can trust",
    scores: { demand: 50, impact: 3, viability: 1, effort: 3 },
    health: "on_track",
    targetStart: "2026-10-01",
    targetEnd: "2026-12-31",
    deliveryLinks: [],
    dependsOn: ["i-stats"],
    visibility: "internal",
    notes: "",
    updatedAt: "2026-06-22T09:30:00Z",
    archived: false,
  },
  {
    id: "i-api-v3",
    title: "Public API v3",
    summary: "A consistent, well-documented REST API covering experiments, flags, and results.",
    problem: "The current API is inconsistent and blocks deeper customer integrations.",
    expectedOutcome: "Partners and customers automate workflows against a stable v3 API.",
    status: "solution_framing",
    ownerId: "u-marc",
    team: "App System",
    themeId: "t-dx",
    strategicGoal: "Open, composable platform",
    scores: { demand: 250, impact: 1, viability: 0.8, effort: 5 },
    health: "on_track",
    targetStart: "2026-08-15",
    targetEnd: "2026-11-30",
    deliveryLinks: [
      { id: "d13", label: "API-88", url: "https://example.atlassian.net/browse/API-88", type: "redmine" },
      { id: "d14", label: "API spec", url: "https://www.notion.so/example/api-v3", type: "notion" },
    ],
    dependsOn: [],
    visibility: "external",
    notes: "",
    updatedAt: "2026-06-27T11:00:00Z",
    archived: false,
  },
  {
    id: "i-ai-insights",
    title: "AI results insights",
    summary: "Natural-language summaries that explain what an experiment's results mean and what to do next.",
    problem: "Interpreting results correctly requires stats expertise many teams lack.",
    expectedOutcome: "Every result ships with a clear, trustworthy recommendation.",
    status: "opportunity_framing",
    ownerId: "u-lea",
    team: "Tech & Perso Builders",
    themeId: "t-ai",
    strategicGoal: "Lead the market on AI-driven experimentation",
    scores: { demand: 1000, impact: 3, viability: 0.5, effort: 8 },
    health: "at_risk",
    targetStart: "2026-11-01",
    targetEnd: "2027-03-31",
    deliveryLinks: [
      { id: "d15", label: "AI-77", url: "https://example.atlassian.net/browse/AI-77", type: "redmine" },
    ],
    dependsOn: ["i-stats"],
    visibility: "internal",
    notes: "Depends on Bayesian GA for reliable inputs.",
    updatedAt: "2026-07-03T14:00:00Z",
    archived: false,
  },
  {
    id: "i-mab",
    title: "Multi-armed bandit optimizer",
    summary: "Auto-allocate traffic to winning variants to reduce regret during a test.",
    problem: "Fixed traffic splits waste conversions on losing variants.",
    expectedOutcome: "Optional bandit mode that maximizes conversions while a test runs.",
    status: "planned",
    ownerId: "u-magali",
    team: "Tech & Perso Builders",
    themeId: "t-ai",
    strategicGoal: "Lead the market on AI-driven experimentation",
    scores: { demand: 250, impact: 3, viability: 0.8, effort: 6 },
    health: "on_track",
    targetStart: "2026-10-15",
    targetEnd: "2027-02-15",
    deliveryLinks: [],
    dependsOn: ["i-stats"],
    visibility: "internal",
    notes: "",
    updatedAt: "2026-06-24T13:00:00Z",
    archived: false,
  },
  {
    id: "i-sdk-docs",
    title: "SDK docs & quickstarts",
    summary: "Rewritten SDK documentation with copy-paste quickstarts for every framework.",
    problem: "Developers stall during integration because docs are outdated and scattered.",
    expectedOutcome: "Time-to-first-SDK-call drops sharply across supported languages.",
    status: "released",
    ownerId: "u-marc",
    team: "App System",
    themeId: "t-dx",
    strategicGoal: "Meet developers where they build",
    scores: { demand: 250, impact: 0.5, viability: 1, effort: 2 },
    health: "on_track",
    targetStart: "2026-04-01",
    targetEnd: "2026-06-15",
    deliveryLinks: [
      { id: "d16", label: "DX-12", url: "https://example.atlassian.net/browse/DX-12", type: "redmine" },
    ],
    dependsOn: [],
    visibility: "external",
    notes: "Shipped; tracking docs bounce rate.",
    updatedAt: "2026-06-16T09:00:00Z",
    archived: false,
  },
];
